// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DCCP_ROC
List DCCP_ROC(arma::mat X, arma::vec Y, arma::vec beta_init, double b_init, double gamma, double psi_k, int max_iter_num, double max_rel_gap);
RcppExport SEXP _imblearn_DCCP_ROC(SEXP XSEXP, SEXP YSEXP, SEXP beta_initSEXP, SEXP b_initSEXP, SEXP gammaSEXP, SEXP psi_kSEXP, SEXP max_iter_numSEXP, SEXP max_rel_gapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< double >::type b_init(b_initSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type psi_k(psi_kSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_num(max_iter_numSEXP);
    Rcpp::traits::input_parameter< double >::type max_rel_gap(max_rel_gapSEXP);
    rcpp_result_gen = Rcpp::wrap(DCCP_ROC(X, Y, beta_init, b_init, gamma, psi_k, max_iter_num, max_rel_gap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imblearn_DCCP_ROC", (DL_FUNC) &_imblearn_DCCP_ROC, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_imblearn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
