# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DCCP_ROC <- function(X, Y, beta_init, b_init, gamma, psi_k, max_iter_num, max_rel_gap) {
    .Call(`_imblearn_DCCP_ROC`, X, Y, beta_init, b_init, gamma, psi_k, max_iter_num, max_rel_gap)
}

DCCP_PR <- function(X, Y, beta_init, b_init, gamma, psi_k, max_iter_num, max_rel_gap) {
    .Call(`_imblearn_DCCP_PR`, X, Y, beta_init, b_init, gamma, psi_k, max_iter_num, max_rel_gap)
}

